spring:
  datasource:
    url: jdbc:h2:mem:coordi
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console